name: jointist
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - setuptools
  - wheel
  - ffmpeg
  - libsndfile
  - sox
  - portaudio
  - pip:
      - torch==2.1.0+cu121
      - torchvision==0.16.0+cu121
      - torchaudio==2.1.0+cu121
      - --extra-index-url https://download.pytorch.org/whl/cu121

      - torchmetrics==0.6.2
      - pytorch_lightning==1.4.5

      - numpy==1.23.5
      - pandas==1.3.5
      - matplotlib==3.5.3
      - tqdm==4.64.1

      - h5py==3.7.0
      - mido==1.2.10
      - pretty_midi==0.2.9
      - pyfluidsynth==1.3.0
      - soundfile>=0.12.1
      - librosa==0.10.0

      - mir_eval==0.6
      - einops==0.6.0
      - black==22.3.0
      - tabulate
      - auditok
      - sox==1.4.1
      - hydra-core==1.3.2

      - git+https://github.com/KinWaiCheuk/slakh_loader